FINANCIAL_VARIABLES = {
    "Revenue": [
        "RevenueFromContractWithCustomerExcludingAssessedTax",
        "Revenues",
        "SalesRevenueNet",
        "RevenueFromContractWithCustomerIncludingAssessedTax",
        "SalesRevenueGoodsNet",
        "SalesRevenueServicesNet",
        "RevenuesNetOfInterestExpense",
        "RevenueFromContractWithCustomer",
    ],
    "Cost of Revenue": [
        "CostOfRevenue",
        "CostOfGoodsAndServicesSold",
        "CostOfGoodsSold",
        "CostOfServices",
        "CostOfGoodsAndServicesExcludingDepreciationDepletionAndAmortization",
    ],
    "Gross Profit": ["GrossProfit"],
    "R&D": [
        "ResearchAndDevelopmentExpense",
        "ResearchAndDevelopmentExpenseExcludingAcquiredInProcessCost",
        "TechnologyAndContentExpenses",
        "ResearchAndDevelopmentExpenseSoftwareExcludingAcquiredInProcessCost",
    ],
    "SG&A": [
        "SellingGeneralAndAdministrativeExpense",
        "SellingGeneralAndAdministrativeExpenseContinuingOperations",
    ],
    "Operating Income": ["OperatingIncomeLoss"],
    "Interest Expense": [
        "InterestExpense",
        "InterestAndDebtExpense",
        "InterestExpenseNonoperating",
        "InterestExpenseDebt",
        "InterestExpenseOperating",
    ],
    "Pre-tax Income": [
        "IncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest",
        "IncomeLossFromContinuingOperationsBeforeIncomeTaxesMinorityInterestAndIncomeLossFromEquityMethodInvestments",
    ],
    "Income Tax": ["IncomeTaxExpenseBenefit"],
    "Net Income": [
        "NetIncomeLoss",
        "ProfitLoss",
        "NetIncomeLossAvailableToCommonStockholdersBasic",
        "IncomeLossFromContinuingOperations",
    ],
    "EPS Basic":   ["EarningsPerShareBasic"],
    "EPS Diluted": ["EarningsPerShareDiluted", "EarningsPerShareBasicAndDiluted"],
    "Cash": [
        "CashAndCashEquivalentsAtCarryingValue",
        "CashCashEquivalentsAndShortTermInvestments",
        "CashAndCashEquivalentsAndShortTermInvestments",
        "Cash",
        "CashAndDueFromBanks",
        "CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents",
    ],
    "Accounts Receivable": [
        "AccountsReceivableNetCurrent",
        "ReceivablesNetCurrent",
        "AccountsNotesAndLoansReceivableNetCurrent",
        "AccountsAndOtherReceivablesNetCurrent",
        "TradeAndOtherReceivablesNetCurrent",
        "BilledContractReceivables",
        "AccountsReceivableNet",
        "NetReceivables",
        "TradeReceivablesNetCurrent",
    ],
    "Inventory": [
        "InventoryNet",
        "EnergyRelatedInventory",
        "PublicUtilitiesInventory",
        "InventoryNetOfAllowancesCustomerAdvancesAndProgressBillings",
    ],
    "Goodwill":            ["Goodwill"],
    "Current Assets":      ["AssetsCurrent"],
    "Total Assets":        ["Assets", "LiabilitiesAndStockholdersEquity"],
    "Current Liabilities": ["LiabilitiesCurrent"],
    "Total Debt": [
        "DebtLongtermAndShorttermCombinedAmount",
        "LongTermDebtAndCapitalLeaseObligations",
        "DebtAndCapitalLeaseObligations",
        "LongTermDebt",
        "LongTermDebtNoncurrent",
        "NotesAndLoansPayable",
        "LongTermNotesAndLoans",
    ],
    "Total Liabilities": ["Liabilities"],
    "Equity": [
        "StockholdersEquity",
        "StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest",
        "PartnersCapital",
        "MembersEquity",
    ],
    "Operating CF": [
        "NetCashProvidedByUsedInOperatingActivities",
        "NetCashProvidedByUsedInOperatingActivitiesContinuingOperations",
    ],
    "CapEx": [
        "PaymentsToAcquirePropertyPlantAndEquipment",
        "PaymentsForCapitalImprovements",
        "PaymentsToAcquireProductiveAssets",
        "PaymentsToAcquireAndDevelopRealEstate",
        "CapitalExpendituresIncurringObligation",
        "PaymentsToAcquirePropertyPlantAndEquipmentAndSoftware",
        "PaymentsToAcquireOtherPropertyPlantAndEquipment",
    ],
    "Depreciation": [
        "DepreciationDepletionAndAmortization",
        "DepreciationAndAmortization",
        "Depreciation",
        "DepreciationAmortizationAndAccretionNet",
        "DepreciationDepletionAndAmortizationPropertyPlantAndEquipment",
    ],
    "Stock-Based Comp": [
        "ShareBasedCompensation",
        "AllocatedShareBasedCompensationExpense",
        "ShareBasedCompensationExpense",
    ],
    "Stock Buybacks": [
        "PaymentsForRepurchaseOfCommonStock",
        "TreasuryStockValueAcquiredCostMethod",
        "PaymentsForRepurchaseOfEquity",
        "PaymentsForRepurchaseOfCommonStockAndPreferredStock",
    ],
    "Dividends Paid": [
        "PaymentsOfDividends",
        "PaymentsOfDividendsCommonStock",
        "PaymentsOfOrdinaryDividends",
        "PaymentsOfDividendsAndDividendEquivalentsOnCommonStockAndRestrictedStockUnits",
    ],
}
